# @req SCI-HELM-002, SCI-HELM-005
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgresql.fullname" . }}-secret
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
type: Opaque
data:
  postgres-password: {{ .Values.auth.password | b64enc | quote }}
  postgres-user: {{ .Values.auth.username | b64enc | quote }}
  postgres-db: {{ .Values.auth.database | b64enc | quote }}
