# @req SCI-HELM-002, SCI-HELM-005
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "api.fullname" . }}-secret
  labels:
    {{- include "api.labels" . | nindent 4 }}
type: Opaque
data:
  db-user: {{ .Values.db.user | b64enc | quote }}
  db-password: {{ .Values.db.password | b64enc | quote }}
  db-name: {{ .Values.db.name | b64enc | quote }}
